// Complete India States, Districts data
// District codes are standardized abbreviations used in DAHD

export const INDIA_DATA = {
  "Andhra Pradesh": {
    code: "AP",
    icarCode: "28",
    districts: [
      { name: "Anantapur", code: "ATP" },
      { name: "Chittoor", code: "CTR" },
      { name: "East Godavari", code: "EGD" },
      { name: "Guntur", code: "GNT" },
      { name: "Krishna", code: "KRS" },
      { name: "Kurnool", code: "KNL" },
      { name: "Nellore", code: "NLR" },
      { name: "Prakasam", code: "PKM" },
      { name: "Srikakulam", code: "SKM" },
      { name: "Visakhapatnam", code: "VZM" },
      { name: "Vizianagaram", code: "VZN" },
      { name: "West Godavari", code: "WGD" },
      { name: "YSR Kadapa", code: "KDP" },
    ]
  },
  "Arunachal Pradesh": {
    code: "AR",
    icarCode: "12",
    districts: [
      { name: "Anjaw", code: "ANJ" },
      { name: "Changlang", code: "CGL" },
      { name: "Dibang Valley", code: "DBV" },
      { name: "East Kameng", code: "EKM" },
      { name: "East Siang", code: "ESG" },
      { name: "Itanagar Capital Complex", code: "ICC" },
      { name: "Kurung Kumey", code: "KKM" },
      { name: "Lohit", code: "LHT" },
      { name: "Longding", code: "LNG" },
      { name: "Lower Dibang Valley", code: "LDV" },
      { name: "Lower Siang", code: "LSG" },
      { name: "Lower Subansiri", code: "LSB" },
      { name: "Namsai", code: "NMS" },
      { name: "Papum Pare", code: "PPR" },
      { name: "Siang", code: "SNG" },
      { name: "Tawang", code: "TWG" },
      { name: "Tirap", code: "TRP" },
      { name: "Upper Dibang Valley", code: "UDV" },
      { name: "Upper Siang", code: "USG" },
      { name: "Upper Subansiri", code: "USB" },
      { name: "West Kameng", code: "WKM" },
      { name: "West Siang", code: "WSG" },
    ]
  },
  "Assam": {
    code: "AS",
    icarCode: "18",
    districts: [
      { name: "Baksa", code: "BKS" },
      { name: "Barpeta", code: "BRP" },
      { name: "Biswanath", code: "BSN" },
      { name: "Bongaigaon", code: "BGN" },
      { name: "Cachar", code: "CCR" },
      { name: "Charaideo", code: "CRD" },
      { name: "Chirang", code: "CRG" },
      { name: "Darrang", code: "DRG" },
      { name: "Dhemaji", code: "DHM" },
      { name: "Dhubri", code: "DHB" },
      { name: "Dibrugarh", code: "DBG" },
      { name: "Dima Hasao", code: "DMH" },
      { name: "Goalpara", code: "GLP" },
      { name: "Golaghat", code: "GLG" },
      { name: "Hailakandi", code: "HLK" },
      { name: "Hojai", code: "HJI" },
      { name: "Jorhat", code: "JRH" },
      { name: "Kamrup", code: "KMP" },
      { name: "Kamrup Metropolitan", code: "KMM" },
      { name: "Karbi Anglong", code: "KBA" },
      { name: "Karimganj", code: "KRG" },
      { name: "Kokrajhar", code: "KKJ" },
      { name: "Lakhimpur", code: "LKP" },
      { name: "Majuli", code: "MJL" },
      { name: "Morigaon", code: "MRG" },
      { name: "Nagaon", code: "NGN" },
      { name: "Nalbari", code: "NLB" },
      { name: "Sivasagar", code: "SSG" },
      { name: "Sonitpur", code: "SNP" },
      { name: "South Salmara Mankachar", code: "SSM" },
      { name: "Tinsukia", code: "TNK" },
      { name: "Udalguri", code: "UDG" },
      { name: "West Karbi Anglong", code: "WKA" },
    ]
  },
  "Bihar": {
    code: "BR",
    icarCode: "10",
    districts: [
      { name: "Araria", code: "ARR" },
      { name: "Arwal", code: "AWL" },
      { name: "Aurangabad", code: "AGB" },
      { name: "Banka", code: "BNK" },
      { name: "Begusarai", code: "BGS" },
      { name: "Bhagalpur", code: "BGL" },
      { name: "Bhojpur", code: "BJP" },
      { name: "Buxar", code: "BXR" },
      { name: "Darbhanga", code: "DBG" },
      { name: "East Champaran", code: "ECP" },
      { name: "Gaya", code: "GYA" },
      { name: "Gopalganj", code: "GPG" },
      { name: "Jamui", code: "JMI" },
      { name: "Jehanabad", code: "JHB" },
      { name: "Kaimur", code: "KMR" },
      { name: "Katihar", code: "KTH" },
      { name: "Khagaria", code: "KGR" },
      { name: "Kishanganj", code: "KSG" },
      { name: "Lakhisarai", code: "LKS" },
      { name: "Madhepura", code: "MDP" },
      { name: "Madhubani", code: "MDB" },
      { name: "Munger", code: "MNG" },
      { name: "Muzaffarpur", code: "MZP" },
      { name: "Nalanda", code: "NLD" },
      { name: "Nawada", code: "NWD" },
      { name: "Patna", code: "PTN" },
      { name: "Purnia", code: "PRN" },
      { name: "Rohtas", code: "RHT" },
      { name: "Saharsa", code: "SHS" },
      { name: "Samastipur", code: "SMP" },
      { name: "Saran", code: "SRN" },
      { name: "Sheikhpura", code: "SKP" },
      { name: "Sheohar", code: "SHR" },
      { name: "Sitamarhi", code: "STM" },
      { name: "Siwan", code: "SWN" },
      { name: "Supaul", code: "SPL" },
      { name: "Vaishali", code: "VSL" },
      { name: "West Champaran", code: "WCP" },
    ]
  },
  "Chhattisgarh": {
    code: "CG",
    icarCode: "22",
    districts: [
      { name: "Balod", code: "BLD" },
      { name: "Baloda Bazar", code: "BLB" },
      { name: "Balrampur", code: "BLP" },
      { name: "Bastar", code: "BST" },
      { name: "Bemetara", code: "BMT" },
      { name: "Bijapur", code: "BJP" },
      { name: "Bilaspur", code: "BLS" },
      { name: "Dantewada", code: "DTW" },
      { name: "Dhamtari", code: "DHT" },
      { name: "Durg", code: "DRG" },
      { name: "Gariaband", code: "GRB" },
      { name: "Gaurela Pendra Marwahi", code: "GPM" },
      { name: "Janjgir Champa", code: "JJC" },
      { name: "Jashpur", code: "JSP" },
      { name: "Kabirdham", code: "KBD" },
      { name: "Kanker", code: "KNK" },
      { name: "Kondagaon", code: "KDG" },
      { name: "Korba", code: "KRB" },
      { name: "Koriya", code: "KRY" },
      { name: "Mahasamund", code: "MHS" },
      { name: "Mungeli", code: "MGL" },
      { name: "Narayanpur", code: "NRP" },
      { name: "Raigarh", code: "RGH" },
      { name: "Raipur", code: "RPR" },
      { name: "Rajnandgaon", code: "RJN" },
      { name: "Sukma", code: "SKM" },
      { name: "Surajpur", code: "SJP" },
      { name: "Surguja", code: "SRG" },
    ]
  },
  "Goa": {
    code: "GA",
    icarCode: "30",
    districts: [
      { name: "North Goa", code: "NGO" },
      { name: "South Goa", code: "SGO" },
    ]
  },
  "Gujarat": {
    code: "GJ",
    icarCode: "24",
    districts: [
      { name: "Ahmedabad", code: "AMD" },
      { name: "Amreli", code: "AML" },
      { name: "Anand", code: "AND" },
      { name: "Aravalli", code: "ARV" },
      { name: "Banaskantha", code: "BNK" },
      { name: "Bharuch", code: "BRC" },
      { name: "Bhavnagar", code: "BVN" },
      { name: "Botad", code: "BTD" },
      { name: "Chhota Udaipur", code: "CUD" },
      { name: "Dahod", code: "DHD" },
      { name: "Dang", code: "DNG" },
      { name: "Devbhoomi Dwarka", code: "DBD" },
      { name: "Gandhinagar", code: "GNR" },
      { name: "Gir Somnath", code: "GRS" },
      { name: "Jamnagar", code: "JMN" },
      { name: "Junagadh", code: "JNG" },
      { name: "Kheda", code: "KHD" },
      { name: "Kutch", code: "KCH" },
      { name: "Mahisagar", code: "MHS" },
      { name: "Mehsana", code: "MSN" },
      { name: "Morbi", code: "MRB" },
      { name: "Narmada", code: "NRM" },
      { name: "Navsari", code: "NVS" },
      { name: "Panchmahal", code: "PCM" },
      { name: "Patan", code: "PTN" },
      { name: "Porbandar", code: "PBD" },
      { name: "Rajkot", code: "RJK" },
      { name: "Sabarkantha", code: "SBK" },
      { name: "Surat", code: "SRT" },
      { name: "Surendranagar", code: "SRN" },
      { name: "Tapi", code: "TPI" },
      { name: "Vadodara", code: "VDR" },
      { name: "Valsad", code: "VLS" },
    ]
  },
  "Haryana": {
    code: "HR",
    icarCode: "06",
    districts: [
      { name: "Ambala", code: "AMB" },
      { name: "Bhiwani", code: "BHW" },
      { name: "Charkhi Dadri", code: "CKD" },
      { name: "Faridabad", code: "FBD" },
      { name: "Fatehabad", code: "FTB" },
      { name: "Gurugram", code: "GGM" },
      { name: "Hisar", code: "HSR" },
      { name: "Jhajjar", code: "JJR" },
      { name: "Jind", code: "JND" },
      { name: "Kaithal", code: "KTL" },
      { name: "Karnal", code: "KNL" },
      { name: "Kurukshetra", code: "KKR" },
      { name: "Mahendragarh", code: "MHG" },
      { name: "Nuh", code: "NUH" },
      { name: "Palwal", code: "PWL" },
      { name: "Panchkula", code: "PKL" },
      { name: "Panipat", code: "PNP" },
      { name: "Rewari", code: "RWR" },
      { name: "Rohtak", code: "RHT" },
      { name: "Sirsa", code: "SRS" },
      { name: "Sonipat", code: "SNP" },
      { name: "Yamunanagar", code: "YMN" },
    ]
  },
  "Himachal Pradesh": {
    code: "HP",
    icarCode: "02",
    districts: [
      { name: "Bilaspur", code: "BLS" },
      { name: "Chamba", code: "CHB" },
      { name: "Hamirpur", code: "HMR" },
      { name: "Kangra", code: "KNG" },
      { name: "Kinnaur", code: "KNR" },
      { name: "Kullu", code: "KLU" },
      { name: "Lahaul Spiti", code: "LHS" },
      { name: "Mandi", code: "MND" },
      { name: "Shimla", code: "SML" },
      { name: "Sirmaur", code: "SRM" },
      { name: "Solan", code: "SLN" },
      { name: "Una", code: "UNA" },
    ]
  },
  "Jharkhand": {
    code: "JH",
    icarCode: "20",
    districts: [
      { name: "Bokaro", code: "BKR" },
      { name: "Chatra", code: "CTR" },
      { name: "Deoghar", code: "DGH" },
      { name: "Dhanbad", code: "DHB" },
      { name: "Dumka", code: "DMK" },
      { name: "East Singhbhum", code: "ESB" },
      { name: "Garhwa", code: "GRW" },
      { name: "Giridih", code: "GRD" },
      { name: "Godda", code: "GDD" },
      { name: "Gumla", code: "GML" },
      { name: "Hazaribagh", code: "HZB" },
      { name: "Jamtara", code: "JMT" },
      { name: "Khunti", code: "KHN" },
      { name: "Koderma", code: "KDM" },
      { name: "Latehar", code: "LTH" },
      { name: "Lohardaga", code: "LHD" },
      { name: "Pakur", code: "PKR" },
      { name: "Palamu", code: "PLM" },
      { name: "Ramgarh", code: "RMG" },
      { name: "Ranchi", code: "RNC" },
      { name: "Sahebganj", code: "SBG" },
      { name: "Seraikela Kharsawan", code: "SKH" },
      { name: "Simdega", code: "SMD" },
      { name: "West Singhbhum", code: "WSB" },
    ]
  },
  "Karnataka": {
    code: "KA",
    icarCode: "29",
    districts: [
      { name: "Bagalkot", code: "BGK" },
      { name: "Ballari", code: "BLR" },
      { name: "Belagavi", code: "BLG" },
      { name: "Bengaluru Rural", code: "BRR" },
      { name: "Bengaluru Urban", code: "BRU" },
      { name: "Bidar", code: "BDR" },
      { name: "Chamarajanagar", code: "CMJ" },
      { name: "Chikkaballapur", code: "CKB" },
      { name: "Chikkamagaluru", code: "CKM" },
      { name: "Chitradurga", code: "CTD" },
      { name: "Dakshina Kannada", code: "DKK" },
      { name: "Davanagere", code: "DVG" },
      { name: "Dharwad", code: "DHW" },
      { name: "Gadag", code: "GDG" },
      { name: "Hassan", code: "HSN" },
      { name: "Haveri", code: "HVR" },
      { name: "Kalaburagi", code: "KLB" },
      { name: "Kodagu", code: "KDG" },
      { name: "Kolar", code: "KLR" },
      { name: "Koppal", code: "KPL" },
      { name: "Mandya", code: "MND" },
      { name: "Mysuru", code: "MYS" },
      { name: "Raichur", code: "RCH" },
      { name: "Ramanagara", code: "RMN" },
      { name: "Shivamogga", code: "SHM" },
      { name: "Tumakuru", code: "TMK" },
      { name: "Udupi", code: "UDP" },
      { name: "Uttara Kannada", code: "UTK" },
      { name: "Vijayapura", code: "VJP" },
      { name: "Yadgir", code: "YDG" },
    ]
  },
  "Kerala": {
    code: "KL",
    icarCode: "32",
    districts: [
      { name: "Alappuzha", code: "ALP" },
      { name: "Ernakulam", code: "EKM" },
      { name: "Idukki", code: "IDK" },
      { name: "Kannur", code: "KNR" },
      { name: "Kasaragod", code: "KSD" },
      { name: "Kollam", code: "KLM" },
      { name: "Kottayam", code: "KTM" },
      { name: "Kozhikode", code: "KZK" },
      { name: "Malappuram", code: "MLP" },
      { name: "Palakkad", code: "PKD" },
      { name: "Pathanamthitta", code: "PTN" },
      { name: "Thiruvananthapuram", code: "TVM" },
      { name: "Thrissur", code: "TSR" },
      { name: "Wayanad", code: "WYD" },
    ]
  },
  "Madhya Pradesh": {
    code: "MP",
    icarCode: "23",
    districts: [
      { name: "Agar Malwa", code: "AGM" },
      { name: "Alirajpur", code: "ARP" },
      { name: "Anuppur", code: "ANP" },
      { name: "Ashoknagar", code: "ASN" },
      { name: "Balaghat", code: "BLG" },
      { name: "Barwani", code: "BRW" },
      { name: "Betul", code: "BTL" },
      { name: "Bhind", code: "BHD" },
      { name: "Bhopal", code: "BPL" },
      { name: "Burhanpur", code: "BHP" },
      { name: "Chhatarpur", code: "CTP" },
      { name: "Chhindwara", code: "CHW" },
      { name: "Damoh", code: "DMH" },
      { name: "Datia", code: "DTA" },
      { name: "Dewas", code: "DWS" },
      { name: "Dhar", code: "DHR" },
      { name: "Dindori", code: "DDR" },
      { name: "Guna", code: "GNA" },
      { name: "Gwalior", code: "GWL" },
      { name: "Harda", code: "HRD" },
      { name: "Hoshangabad", code: "HSB" },
      { name: "Indore", code: "IDR" },
      { name: "Jabalpur", code: "JBP" },
      { name: "Jhabua", code: "JHB" },
      { name: "Katni", code: "KTN" },
      { name: "Khandwa", code: "KHW" },
      { name: "Khargone", code: "KRG" },
      { name: "Mandla", code: "MDL" },
      { name: "Mandsaur", code: "MDS" },
      { name: "Morena", code: "MRN" },
      { name: "Narsinghpur", code: "NSP" },
      { name: "Neemuch", code: "NMC" },
      { name: "Niwari", code: "NWR" },
      { name: "Panna", code: "PNA" },
      { name: "Raisen", code: "RSN" },
      { name: "Rajgarh", code: "RJG" },
      { name: "Ratlam", code: "RTM" },
      { name: "Rewa", code: "RWA" },
      { name: "Sagar", code: "SGR" },
      { name: "Satna", code: "STN" },
      { name: "Sehore", code: "SHR" },
      { name: "Seoni", code: "SNI" },
      { name: "Shahdol", code: "SHD" },
      { name: "Shajapur", code: "SJP" },
      { name: "Sheopur", code: "SHP" },
      { name: "Shivpuri", code: "SWP" },
      { name: "Sidhi", code: "SDH" },
      { name: "Singrauli", code: "SGL" },
      { name: "Tikamgarh", code: "TKG" },
      { name: "Ujjain", code: "UJN" },
      { name: "Umaria", code: "UMR" },
      { name: "Vidisha", code: "VDS" },
    ]
  },
  "Maharashtra": {
    code: "MH",
    icarCode: "27",
    districts: [
      { name: "Ahmednagar", code: "AHN" },
      { name: "Akola", code: "AKL" },
      { name: "Amravati", code: "AMV" },
      { name: "Aurangabad", code: "AGB" },
      { name: "Beed", code: "BED" },
      { name: "Bhandara", code: "BND" },
      { name: "Buldhana", code: "BLD" },
      { name: "Chandrapur", code: "CDP" },
      { name: "Dhule", code: "DHL" },
      { name: "Gadchiroli", code: "GDC" },
      { name: "Gondia", code: "GND" },
      { name: "Hingoli", code: "HGL" },
      { name: "Jalgaon", code: "JLG" },
      { name: "Jalna", code: "JLN" },
      { name: "Kolhapur", code: "KLP" },
      { name: "Latur", code: "LTR" },
      { name: "Mumbai City", code: "MBC" },
      { name: "Mumbai Suburban", code: "MBS" },
      { name: "Nagpur", code: "NGP" },
      { name: "Nanded", code: "NND" },
      { name: "Nandurbar", code: "NDB" },
      { name: "Nashik", code: "NSK" },
      { name: "Osmanabad", code: "OSM" },
      { name: "Palghar", code: "PLG" },
      { name: "Parbhani", code: "PRB" },
      { name: "Pune", code: "PUN" },
      { name: "Raigad", code: "RGD" },
      { name: "Ratnagiri", code: "RTG" },
      { name: "Sangli", code: "SGL" },
      { name: "Satara", code: "STR" },
      { name: "Sindhudurg", code: "SDG" },
      { name: "Solapur", code: "SLP" },
      { name: "Thane", code: "THN" },
      { name: "Wardha", code: "WRD" },
      { name: "Washim", code: "WSM" },
      { name: "Yavatmal", code: "YTM" },
    ]
  },
  "Manipur": {
    code: "MN",
    icarCode: "14",
    districts: [
      { name: "Bishnupur", code: "BSP" },
      { name: "Chandel", code: "CDL" },
      { name: "Churachandpur", code: "CCP" },
      { name: "Imphal East", code: "IME" },
      { name: "Imphal West", code: "IMW" },
      { name: "Jiribam", code: "JRB" },
      { name: "Kakching", code: "KKC" },
      { name: "Kamjong", code: "KMJ" },
      { name: "Kangpokpi", code: "KGP" },
      { name: "Noney", code: "NNY" },
      { name: "Pherzawl", code: "PHZ" },
      { name: "Senapati", code: "SNP" },
      { name: "Tamenglong", code: "TML" },
      { name: "Tengnoupal", code: "TGP" },
      { name: "Thoubal", code: "TBL" },
      { name: "Ukhrul", code: "UKL" },
    ]
  },
  "Meghalaya": {
    code: "ML",
    icarCode: "17",
    districts: [
      { name: "East Garo Hills", code: "EGH" },
      { name: "East Jaintia Hills", code: "EJH" },
      { name: "East Khasi Hills", code: "EKH" },
      { name: "North Garo Hills", code: "NGH" },
      { name: "Ri Bhoi", code: "RBH" },
      { name: "South Garo Hills", code: "SGH" },
      { name: "South West Garo Hills", code: "SWG" },
      { name: "South West Khasi Hills", code: "SWK" },
      { name: "West Garo Hills", code: "WGH" },
      { name: "West Jaintia Hills", code: "WJH" },
      { name: "West Khasi Hills", code: "WKH" },
    ]
  },
  "Mizoram": {
    code: "MZ",
    icarCode: "15",
    districts: [
      { name: "Aizawl", code: "AZL" },
      { name: "Champhai", code: "CHP" },
      { name: "Hnahthial", code: "HNT" },
      { name: "Khawzawl", code: "KHZ" },
      { name: "Kolasib", code: "KLS" },
      { name: "Lawngtlai", code: "LWT" },
      { name: "Lunglei", code: "LGL" },
      { name: "Mamit", code: "MMT" },
      { name: "Saiha", code: "SHH" },
      { name: "Saitual", code: "STL" },
      { name: "Serchhip", code: "SCP" },
    ]
  },
  "Nagaland": {
    code: "NL",
    icarCode: "13",
    districts: [
      { name: "Dimapur", code: "DMP" },
      { name: "Kiphire", code: "KPH" },
      { name: "Kohima", code: "KHM" },
      { name: "Longleng", code: "LLG" },
      { name: "Mokokchung", code: "MKC" },
      { name: "Mon", code: "MON" },
      { name: "Noklak", code: "NLK" },
      { name: "Peren", code: "PRN" },
      { name: "Phek", code: "PHK" },
      { name: "Tuensang", code: "TSG" },
      { name: "Wokha", code: "WKH" },
      { name: "Zunheboto", code: "ZHB" },
    ]
  },
  "Odisha": {
    code: "OD",
    icarCode: "21",
    districts: [
      { name: "Angul", code: "AGL" },
      { name: "Balangir", code: "BLG" },
      { name: "Balasore", code: "BLS" },
      { name: "Bargarh", code: "BRG" },
      { name: "Bhadrak", code: "BDK" },
      { name: "Boudh", code: "BDH" },
      { name: "Cuttack", code: "CTK" },
      { name: "Deogarh", code: "DGH" },
      { name: "Dhenkanal", code: "DKL" },
      { name: "Gajapati", code: "GJP" },
      { name: "Ganjam", code: "GNJ" },
      { name: "Jagatsinghpur", code: "JSP" },
      { name: "Jajpur", code: "JJP" },
      { name: "Jharsuguda", code: "JHG" },
      { name: "Kalahandi", code: "KLH" },
      { name: "Kandhamal", code: "KDM" },
      { name: "Kendrapara", code: "KNP" },
      { name: "Kendujhar", code: "KNJ" },
      { name: "Khordha", code: "KHD" },
      { name: "Koraput", code: "KRP" },
      { name: "Malkangiri", code: "MLK" },
      { name: "Mayurbhanj", code: "MYB" },
      { name: "Nabarangpur", code: "NBP" },
      { name: "Nayagarh", code: "NYG" },
      { name: "Nuapada", code: "NPD" },
      { name: "Puri", code: "PRI" },
      { name: "Rayagada", code: "RYG" },
      { name: "Sambalpur", code: "SBP" },
      { name: "Subarnapur", code: "SBN" },
      { name: "Sundargarh", code: "SDG" },
    ]
  },
  "Punjab": {
    code: "PB",
    icarCode: "03",
    districts: [
      { name: "Amritsar", code: "AMR" },
      { name: "Barnala", code: "BNL" },
      { name: "Bathinda", code: "BTD" },
      { name: "Faridkot", code: "FDK" },
      { name: "Fatehgarh Sahib", code: "FGS" },
      { name: "Fazilka", code: "FZK" },
      { name: "Ferozepur", code: "FZP" },
      { name: "Gurdaspur", code: "GDP" },
      { name: "Hoshiarpur", code: "HSP" },
      { name: "Jalandhar", code: "JLD" },
      { name: "Kapurthala", code: "KPT" },
      { name: "Ludhiana", code: "LDH" },
      { name: "Malerkotla", code: "MLK" },
      { name: "Mansa", code: "MNS" },
      { name: "Moga", code: "MGA" },
      { name: "Muktsar", code: "MKT" },
      { name: "Nawanshahr", code: "NWS" },
      { name: "Pathankot", code: "PTK" },
      { name: "Patiala", code: "PTL" },
      { name: "Rupnagar", code: "RPN" },
      { name: "Sangrur", code: "SGR" },
      { name: "SAS Nagar", code: "SAS" },
      { name: "Tarn Taran", code: "TTN" },
    ]
  },
  "Rajasthan": {
    code: "RJ",
    icarCode: "08",
    districts: [
      { name: "Ajmer", code: "AJM" },
      { name: "Alwar", code: "ALW" },
      { name: "Banswara", code: "BNS" },
      { name: "Baran", code: "BRN" },
      { name: "Barmer", code: "BRM" },
      { name: "Bharatpur", code: "BTP" },
      { name: "Bhilwara", code: "BHW" },
      { name: "Bikaner", code: "BKN" },
      { name: "Bundi", code: "BND" },
      { name: "Chittorgarh", code: "CTG" },
      { name: "Churu", code: "CHR" },
      { name: "Dausa", code: "DSA" },
      { name: "Dholpur", code: "DHP" },
      { name: "Dungarpur", code: "DGP" },
      { name: "Hanumangarh", code: "HMG" },
      { name: "Jaipur", code: "JPR" },
      { name: "Jaisalmer", code: "JSM" },
      { name: "Jalore", code: "JLR" },
      { name: "Jhalawar", code: "JHW" },
      { name: "Jhunjhunu", code: "JJN" },
      { name: "Jodhpur", code: "JDH" },
      { name: "Karauli", code: "KRL" },
      { name: "Kota", code: "KTA" },
      { name: "Nagaur", code: "NGR" },
      { name: "Pali", code: "PLI" },
      { name: "Pratapgarh", code: "PTP" },
      { name: "Rajsamand", code: "RJS" },
      { name: "Sawai Madhopur", code: "SWM" },
      { name: "Sikar", code: "SKR" },
      { name: "Sirohi", code: "SRH" },
      { name: "Sri Ganganagar", code: "SGN" },
      { name: "Tonk", code: "TNK" },
      { name: "Udaipur", code: "UDP" },
    ]
  },
  "Sikkim": {
    code: "SK",
    icarCode: "11",
    districts: [
      { name: "East Sikkim", code: "ESK" },
      { name: "North Sikkim", code: "NSK" },
      { name: "Pakyong", code: "PKY" },
      { name: "Soreng", code: "SRG" },
      { name: "South Sikkim", code: "SSK" },
      { name: "West Sikkim", code: "WSK" },
    ]
  },
  "Tamil Nadu": {
    code: "TN",
    icarCode: "33",
    districts: [
      { name: "Ariyalur", code: "ARL" },
      { name: "Chengalpattu", code: "CGP" },
      { name: "Chennai", code: "CHN" },
      { name: "Coimbatore", code: "CBE" },
      { name: "Cuddalore", code: "CDL" },
      { name: "Dharmapuri", code: "DHP" },
      { name: "Dindigul", code: "DDG" },
      { name: "Erode", code: "ERD" },
      { name: "Kallakurichi", code: "KLK" },
      { name: "Kancheepuram", code: "KCP" },
      { name: "Karur", code: "KRR" },
      { name: "Krishnagiri", code: "KRG" },
      { name: "Madurai", code: "MDU" },
      { name: "Mayiladuthurai", code: "MYD" },
      { name: "Nagapattinam", code: "NGP" },
      { name: "Namakkal", code: "NMK" },
      { name: "Nilgiris", code: "NLG" },
      { name: "Perambalur", code: "PBR" },
      { name: "Pudukkottai", code: "PDK" },
      { name: "Ramanathapuram", code: "RMN" },
      { name: "Ranipet", code: "RNP" },
      { name: "Salem", code: "SLM" },
      { name: "Sivaganga", code: "SVG" },
      { name: "Tenkasi", code: "TKS" },
      { name: "Thanjavur", code: "TJV" },
      { name: "Theni", code: "THN" },
      { name: "Thoothukudi", code: "TTK" },
      { name: "Tiruchirappalli", code: "TRY" },
      { name: "Tirunelveli", code: "TNV" },
      { name: "Tirupathur", code: "TPT" },
      { name: "Tiruppur", code: "TRP" },
      { name: "Tiruvallur", code: "TVL" },
      { name: "Tiruvannamalai", code: "TVM" },
      { name: "Tiruvarur", code: "TVR" },
      { name: "Vellore", code: "VLR" },
      { name: "Viluppuram", code: "VLP" },
      { name: "Virudhunagar", code: "VRD" },
    ]
  },
  "Telangana": {
    code: "TS",
    icarCode: "36",
    districts: [
      { name: "Adilabad", code: "ADB" },
      { name: "Bhadradri Kothagudem", code: "BKG" },
      { name: "Hanumakonda", code: "HMK" },
      { name: "Hyderabad", code: "HYD" },
      { name: "Jagitial", code: "JGT" },
      { name: "Jangaon", code: "JGN" },
      { name: "Jayashankar Bhupalpally", code: "JBP" },
      { name: "Jogulamba Gadwal", code: "JGW" },
      { name: "Kamareddy", code: "KMR" },
      { name: "Karimnagar", code: "KRN" },
      { name: "Khammam", code: "KHM" },
      { name: "Komaram Bheem Asifabad", code: "KBA" },
      { name: "Mahabubabad", code: "MBB" },
      { name: "Mahabubnagar", code: "MBN" },
      { name: "Mancherial", code: "MCH" },
      { name: "Medak", code: "MDK" },
      { name: "Medchal Malkajgiri", code: "MMK" },
      { name: "Mulugu", code: "MLG" },
      { name: "Nagarkurnool", code: "NKL" },
      { name: "Nalgonda", code: "NLG" },
      { name: "Narayanpet", code: "NRP" },
      { name: "Nirmal", code: "NRM" },
      { name: "Nizamabad", code: "NZB" },
      { name: "Peddapalli", code: "PDL" },
      { name: "Rajanna Sircilla", code: "RSC" },
      { name: "Rangareddy", code: "RRD" },
      { name: "Sangareddy", code: "SGD" },
      { name: "Siddipet", code: "SDP" },
      { name: "Suryapet", code: "SRP" },
      { name: "Vikarabad", code: "VKB" },
      { name: "Wanaparthy", code: "WNP" },
      { name: "Warangal", code: "WGL" },
      { name: "Yadadri Bhuvanagiri", code: "YDB" },
    ]
  },
  "Tripura": {
    code: "TR",
    icarCode: "16",
    districts: [
      { name: "Dhalai", code: "DHL" },
      { name: "Gomati", code: "GMT" },
      { name: "Khowai", code: "KHW" },
      { name: "North Tripura", code: "NTR" },
      { name: "Sepahijala", code: "SPJ" },
      { name: "South Tripura", code: "STR" },
      { name: "Unakoti", code: "UNK" },
      { name: "West Tripura", code: "WTR" },
    ]
  },
  "Uttar Pradesh": {
    code: "UP",
    icarCode: "09",
    districts: [
      { name: "Agra", code: "AGR" },
      { name: "Aligarh", code: "ALG" },
      { name: "Ambedkar Nagar", code: "ABN" },
      { name: "Amethi", code: "AMT" },
      { name: "Amroha", code: "AMR" },
      { name: "Auraiya", code: "ARY" },
      { name: "Ayodhya", code: "AYD" },
      { name: "Azamgarh", code: "AZG" },
      { name: "Baghpat", code: "BGP" },
      { name: "Bahraich", code: "BHC" },
      { name: "Ballia", code: "BLL" },
      { name: "Balrampur", code: "BLP" },
      { name: "Banda", code: "BND" },
      { name: "Barabanki", code: "BBK" },
      { name: "Bareilly", code: "BRL" },
      { name: "Basti", code: "BST" },
      { name: "Bhadohi", code: "BDH" },
      { name: "Bijnor", code: "BJN" },
      { name: "Budaun", code: "BDN" },
      { name: "Bulandshahr", code: "BLD" },
      { name: "Chandauli", code: "CDL" },
      { name: "Chitrakoot", code: "CTK" },
      { name: "Deoria", code: "DRA" },
      { name: "Etah", code: "ETH" },
      { name: "Etawah", code: "ETW" },
      { name: "Farrukhabad", code: "FKB" },
      { name: "Fatehpur", code: "FTP" },
      { name: "Firozabad", code: "FZB" },
      { name: "Gautam Buddha Nagar", code: "GBN" },
      { name: "Ghaziabad", code: "GZB" },
      { name: "Ghazipur", code: "GZP" },
      { name: "Gonda", code: "GND" },
      { name: "Gorakhpur", code: "GKP" },
      { name: "Hamirpur", code: "HMP" },
      { name: "Hapur", code: "HPR" },
      { name: "Hardoi", code: "HDI" },
      { name: "Hathras", code: "HTH" },
      { name: "Jalaun", code: "JLN" },
      { name: "Jaunpur", code: "JNP" },
      { name: "Jhansi", code: "JHS" },
      { name: "Kannauj", code: "KNJ" },
      { name: "Kanpur Dehat", code: "KPD" },
      { name: "Kanpur Nagar", code: "KPN" },
      { name: "Kasganj", code: "KSG" },
      { name: "Kaushambi", code: "KSB" },
      { name: "Kheri", code: "KHR" },
      { name: "Kushinagar", code: "KSN" },
      { name: "Lalitpur", code: "LLP" },
      { name: "Lucknow", code: "LKO" },
      { name: "Maharajganj", code: "MRJ" },
      { name: "Mahoba", code: "MHB" },
      { name: "Mainpuri", code: "MNP" },
      { name: "Mathura", code: "MTH" },
      { name: "Mau", code: "MAU" },
      { name: "Meerut", code: "MRT" },
      { name: "Mirzapur", code: "MZP" },
      { name: "Moradabad", code: "MRD" },
      { name: "Muzaffarnagar", code: "MZN" },
      { name: "Pilibhit", code: "PLB" },
      { name: "Pratapgarh", code: "PTP" },
      { name: "Prayagraj", code: "PRG" },
      { name: "Raebareli", code: "RBL" },
      { name: "Rampur", code: "RMP" },
      { name: "Saharanpur", code: "SHN" },
      { name: "Sambhal", code: "SMB" },
      { name: "Sant Kabir Nagar", code: "SKN" },
      { name: "Shahjahanpur", code: "SJP" },
      { name: "Shamli", code: "SML" },
      { name: "Shravasti", code: "SRV" },
      { name: "Siddharthnagar", code: "SDN" },
      { name: "Sitapur", code: "STP" },
      { name: "Sonbhadra", code: "SNB" },
      { name: "Sultanpur", code: "SLT" },
      { name: "Unnao", code: "UNN" },
      { name: "Varanasi", code: "VNS" },
    ]
  },
  "Uttarakhand": {
    code: "UK",
    icarCode: "05",
    districts: [
      { name: "Almora", code: "ALM" },
      { name: "Bageshwar", code: "BGS" },
      { name: "Chamoli", code: "CML" },
      { name: "Champawat", code: "CMP" },
      { name: "Dehradun", code: "DDN" },
      { name: "Haridwar", code: "HDW" },
      { name: "Nainital", code: "NNT" },
      { name: "Pauri Garhwal", code: "PGW" },
      { name: "Pithoragarh", code: "PTG" },
      { name: "Rudraprayag", code: "RDP" },
      { name: "Tehri Garhwal", code: "TGW" },
      { name: "Udham Singh Nagar", code: "USN" },
      { name: "Uttarkashi", code: "UTK" },
    ]
  },
  "West Bengal": {
    code: "WB",
    icarCode: "19",
    districts: [
      { name: "Alipurduar", code: "APD" },
      { name: "Bankura", code: "BNK" },
      { name: "Birbhum", code: "BRB" },
      { name: "Cooch Behar", code: "CBH" },
      { name: "Dakshin Dinajpur", code: "DDJ" },
      { name: "Darjeeling", code: "DJL" },
      { name: "Hooghly", code: "HGL" },
      { name: "Howrah", code: "HWH" },
      { name: "Jalpaiguri", code: "JLG" },
      { name: "Jhargram", code: "JGM" },
      { name: "Kalimpong", code: "KLP" },
      { name: "Kolkata", code: "KLK" },
      { name: "Malda", code: "MLD" },
      { name: "Murshidabad", code: "MSB" },
      { name: "Nadia", code: "NDI" },
      { name: "North 24 Parganas", code: "NTP" },
      { name: "Paschim Bardhaman", code: "PWB" },
      { name: "Paschim Medinipur", code: "PWM" },
      { name: "Purba Bardhaman", code: "PBD" },
      { name: "Purba Medinipur", code: "PBM" },
      { name: "Purulia", code: "PRL" },
      { name: "South 24 Parganas", code: "STP" },
      { name: "Uttar Dinajpur", code: "UDP" },
    ]
  },
  "Andaman and Nicobar Islands": {
    code: "AN",
    icarCode: "35",
    districts: [
      { name: "Nicobar", code: "NCB" },
      { name: "North and Middle Andaman", code: "NMA" },
      { name: "South Andaman", code: "SAN" },
    ]
  },
  "Chandigarh": {
    code: "CH",
    icarCode: "04",
    districts: [
      { name: "Chandigarh", code: "CHD" },
    ]
  },
  "Dadra and Nagar Haveli and Daman and Diu": {
    code: "DD",
    icarCode: "26",
    districts: [
      { name: "Dadra and Nagar Haveli", code: "DNH" },
      { name: "Daman", code: "DMN" },
      { name: "Diu", code: "DIU" },
    ]
  },
  "Delhi": {
    code: "DL",
    icarCode: "07",
    districts: [
      { name: "Central Delhi", code: "CDL" },
      { name: "East Delhi", code: "EDL" },
      { name: "New Delhi", code: "NDL" },
      { name: "North Delhi", code: "NND" },
      { name: "North East Delhi", code: "NED" },
      { name: "North West Delhi", code: "NWD" },
      { name: "Shahdara", code: "SHD" },
      { name: "South Delhi", code: "SDL" },
      { name: "South East Delhi", code: "SED" },
      { name: "South West Delhi", code: "SWD" },
      { name: "West Delhi", code: "WDL" },
    ]
  },
  "Jammu and Kashmir": {
    code: "JK",
    icarCode: "01",
    districts: [
      { name: "Anantnag", code: "ANG" },
      { name: "Bandipora", code: "BDP" },
      { name: "Baramulla", code: "BRM" },
      { name: "Budgam", code: "BDG" },
      { name: "Doda", code: "DDA" },
      { name: "Ganderbal", code: "GDB" },
      { name: "Jammu", code: "JMU" },
      { name: "Kathua", code: "KTH" },
      { name: "Kishtwar", code: "KSW" },
      { name: "Kulgam", code: "KLG" },
      { name: "Kupwara", code: "KPW" },
      { name: "Poonch", code: "PNC" },
      { name: "Pulwama", code: "PLW" },
      { name: "Rajouri", code: "RJR" },
      { name: "Ramban", code: "RMB" },
      { name: "Reasi", code: "RSI" },
      { name: "Samba", code: "SMB" },
      { name: "Shopian", code: "SHP" },
      { name: "Srinagar", code: "SRN" },
      { name: "Udhampur", code: "UDP" },
    ]
  },
  "Ladakh": {
    code: "LA",
    icarCode: "38",
    districts: [
      { name: "Kargil", code: "KGL" },
      { name: "Leh", code: "LEH" },
    ]
  },
  "Lakshadweep": {
    code: "LD",
    icarCode: "31",
    districts: [
      { name: "Lakshadweep", code: "LKW" },
    ]
  },
  "Puducherry": {
    code: "PY",
    icarCode: "34",
    districts: [
      { name: "Karaikal", code: "KKL" },
      { name: "Mahe", code: "MHE" },
      { name: "Puducherry", code: "PDC" },
      { name: "Yanam", code: "YNM" },
    ]
  },
}

export const STATE_NAMES = Object.keys(INDIA_DATA).sort()

export const getStateCode = (stateName) => INDIA_DATA[stateName]?.code || ''

export const getIcarStateCode = (stateName) => INDIA_DATA[stateName]?.icarCode || '00'

export const getDistricts = (stateName) => INDIA_DATA[stateName]?.districts || []

export const getDistrictCode = (stateName, districtName) => {
  const districts = getDistricts(stateName)
  return districts.find(d => d.name === districtName)?.code || ''
}

// Generate ICAR tag: IN + 2-digit state code + 3-digit farm sequence + 5-digit random
// Total = 2 + 2 + 3 + 5 = 12 characters
export const generateIcarTag = (stateName, farmSequence = null) => {
  const stateCode = getIcarStateCode(stateName)  // e.g. "27"
  const farmSeq = farmSequence
    ? String(farmSequence).padStart(3, '0')       // e.g. "001"
    : String(Math.floor(Math.random() * 999) + 1).padStart(3, '0')
  const serial = String(Math.floor(Math.random() * 99999) + 1).padStart(5, '0') // e.g. "04521"
  return `IN${stateCode}${farmSeq}${serial}`
}